apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wog7mz0ic-java-quarkus
  janus-idp.io/tekton: wog7mz0ic-java-quarkus
  backstage.io/kubernetes-id: wog7mz0ic-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wog7mz0ic-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
