apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wog7mz0ic-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/wog7mz0ic-java-quarkus-gitops